import type { Metadata } from "next";
import MetaConsole from "next-meta-console";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="p-6">
        {children}
        <MetaConsole />
      </body>
    </html>
  );
}
