import type { Metadata } from "next";
import NextMetaConsole from "next-meta-console";
import "next-meta-console/dist/main.css";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="p-6">
        {children}
        <NextMetaConsole enabled={process.env.NODE_ENV === "development"} />
      </body>
    </html>
  );
}
